name: Automate Route 53 Update

on:
 push:
   branches:
     - main
jobs:
  aws_route53:
    runs-on: ubuntu-latest
    steps:
      - name: "Create an A record set"
        uses: Roosterfish/aws-route53-record-set-action@master
        with: 
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_route53_hosted_zone_id: ${{ secrets.AWS_ROUTE53_HOSTED_ZONE_ID }}
env:
  AWS_ROUTE53_RR_NAME: ${{ github.event.inputs.domain_name }}
  AWS_ROUTE53_RR_TYPE: A
  AWS_ROUTE53_RR_TTL: 300
  AWS_ROUTE53_RR_VALUE: ${{ github.event.inputs.server_ip }}
